# Generated by Django 4.0.6 on 2023-01-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
