# Generated by Django 4.0.6 on 2023-01-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=None, max_length=8, null=True),
        ),
    ]
