# Generated by Django 4.0.6 on 2023-01-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='presc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
