# Generated by Django 4.0.6 on 2023-01-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_prescription_next_visit_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='next_visit',
        ),
    ]
