# Generated by Django 4.0.6 on 2023-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_prescription_next_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
