# Generated by Django 4.0.6 on 2023-01-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_appointment_pstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=None, max_length=8, null=True),
        ),
    ]
