# Generated by Django 4.0.6 on 2023-01-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_invoice_accountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='astatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
