# Generated by Django 4.0.6 on 2023-01-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_appointment_astatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
