# Generated by Django 4.0.6 on 2023-01-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_invoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.accountant'),
        ),
    ]
