# Generated by Django 4.0.6 on 2023-01-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_astatus_appointment_istatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
