# Generated by Django 4.0.6 on 2023-01-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_appointment_app_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
