# Generated by Django 4.0.6 on 2023-01-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_appointment_app_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
