# Generated by Django 4.0.6 on 2023-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_appointment_app_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='istatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
